// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDehKVP3oJe9SViNdF3F4Ad6UayzXnDvqY',
    appId: '1:1098947487924:web:9f5ee343b70477773e4fe1',
    messagingSenderId: '1098947487924',
    projectId: 'new-jarvis-725d8',
    authDomain: 'new-jarvis-725d8.firebaseapp.com',
    storageBucket: 'new-jarvis-725d8.appspot.com',
    measurementId: 'G-CLESZKB8HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI_SCLv6ViZ2vLMTvWIS6_8Bd18xQPeJI',
    appId: '1:1098947487924:android:8a3b00dc92a278fc3e4fe1',
    messagingSenderId: '1098947487924',
    projectId: 'new-jarvis-725d8',
    storageBucket: 'new-jarvis-725d8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDehKVP3oJe9SViNdF3F4Ad6UayzXnDvqY',
    appId: '1:1098947487924:web:0072527c80e687083e4fe1',
    messagingSenderId: '1098947487924',
    projectId: 'new-jarvis-725d8',
    authDomain: 'new-jarvis-725d8.firebaseapp.com',
    storageBucket: 'new-jarvis-725d8.appspot.com',
    measurementId: 'G-2M22QKM7FD',
  );
}
